github: cat-cols
patreon: # Replace with your username
open_collective: # Replace with your username
ko_fi: # Replace with your username
tidelift: # Replace with your package name
community_bridge: # Replace with your project name
liberapay: # Replace with your username
issuehunt: # Replace with your username
otechie: # Replace with your username
custom: # Replace with your URL